- name: Setting up backend
  hosts: localhost
  become: yes
  vars:

  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: useradd expense
      ansible.builtin.user:
       name: expense

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download app code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: unzip code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip # by default checks in ansible server
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.command: npm install

    - name: Setup SystemD Expense Backend Service
      ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable backend service
      ansible.builtin.service:
        name: backend
        state: started
        enabled: yes